### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by mbojan** [cmarcum/halftoner#1]
Apart from the appreciation (very cool!) I was curious why did you implement `plot()`-ing and `points()`-ing using S4 given that `halftone()` returns an S3 object?

cheers,
michal

PS. Your keyboard seems to have the `SPACE` key broken... ;)

**Comment by cmarcum** [comment]
i intend to have it return an S4 , i just haven't pushed the fix. you can
see in the commented-out section of the source code that i started with S3
methods and then switched midway.lol. I'm indecisive.

methods.skeleton doesn't do a great job interesting ones intentions.

**Comment by cmarcum** [comment]
oh and feel free to make a pull request top patch it yourself! happy to
have contribs

**Comment by mbojan** [comment]
i'd stay away from S4 unless (1) you need multiple dispatch or (2) exercise or (3) "shits & giggles"

**Comment by cmarcum** [comment]
Hey Michal, I've updated to export only S3 methods/classes now. Thanks for the tip.
